task/urls.py
from django.urls import path
from .views import (TaskListView,
                    TaskDetailView,
                    TaskCreateView,
                    TaskUpdateView,
                    TaskDeleteView,
                    TaskOrderView
                    )

app_name = 'task'

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update', TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete', TaskDeleteView.as_view(), name='task-delete'),
    path('create/', TaskCreateView.as_view(), name='task-create'),
    path('task_order/', TaskOrderView.as_view(), name='task-order')
]

todoapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from task.views import RegisterView, UserLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    complete = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        order_with_respect_to = 'user'

task/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic, View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db import transaction

from .models import Task
from .froms import TaskForm, TaskOrderingForm

class LandingPageView(generic.TemplateView):
    template_name = 'landing.html'


class RegisterView(generic.CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse('task:task-list')


class UserLoginView(LoginView):
    template_name = 'registration/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse('task:task-list')


class TaskListView(LoginRequiredMixin, generic.ListView):
    template_name = 'task/task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        user = self.request.user
        queryset = Task.objects.filter(user=user)

        search_query = self.request.GET.get('search') or ''
        if search_query:
            queryset = queryset.filter(title__icontains=search_query)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['incomplete_tasks_count'] = Task.objects.filter(user=self.request.user, complete=False).count()

        return context


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'task/task_detail.html'
    context_object_name = 'task'

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(user=user)


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'task/task_create.html'
    form_class = TaskForm

    def get_success_url(self):
        return reverse('task:task-list')


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'task/task_update.html'
    form_class = TaskForm

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(user=user)

    def get_success_url(self):
        return reverse('task:task-list')


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'task/task_delete.html'
    context_object_name = 'task'

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(user=user)

    def get_success_url(self):
        return reverse('task:task-list')


class TaskOrderView(LoginRequiredMixin, View):
    def post(self, request):
        form = TaskOrderingForm(request.POST)

        if form.is_valid():
            ordered = form.cleaned_data['position'].split(',')

        with transaction.atomic():
            self.request.user.set_task_order(ordered)

        return redirect('task:task-list')

task/templates/task/task_create.html
{% extends 'base.html' %}

{% block content %}

<div class="header-bar">
    <a href="{% url 'task:task-list' %}">&#8617; Back</a>
</div>

<div class="card-body">
<h3>Create New Task:</h3>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="button" type="submit">
</form>
</div>

{% endblock %}

task/templates/task/task_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="header-bar">
  <a href="{% url 'task:task-list' %}">&#8617; Go Back</a>
</div>

<div class="card-body">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input class="button" type="submit" value="Yes, delete">
  </form>
</div>



{% endblock %}

task/templates/task/task_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="header-bar">
    <a href="{% url 'task:task-list' %}">&#8592; Back</a>
</div>

<h1>Task: {{ task.title }}</h1>

<p>Description: {{ task.description }}</p>
<a href="{% url 'task:task-list' %}">Go back to task list</a>
{% endblock %}

task/templates/task/task_list.html
{% extends 'base.html' %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<div class="header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin:0">You have <i>{{incomplete_tasks_count}}</i> incomplete task{{ incomplete_tasks_count|pluralize:"s" }}</h3>
    </div>

    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>


<div id="search-add-wrapper">
    <form method="GET" style="display: flex;">
        <input type='text' name='search-area' placeholder="Search your task" value="{{search_input}}">
        <input class="button" type="submit" value='Search'>
    </form>
    {% if tasks|length > 0 %}
    <a id="add-link" href="{% url 'task:task-create' %}">&#x2b;</a>
    {% endif %}
</div>



<form style="display: none;" id="orderTask" method="post" action="{% url 'task:task-order' %}">
    {% csrf_token %}
    <input type="hidden" id="positionInput" name="position">
</form>


<div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper" data-position="{{task.pk}}">
        <div class="task-title">
            {% if task.complete %}
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'task:task-update' task.id %}">{{task}}</a></s></i>
            {% else %}
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'task:task-update' task.id %}">{{task}}</a>
            {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'task:task-delete' task.id %}">&#10007;</a>
            <span class="handle">&nbsp;&#8661;</span>
        </div>
    </div>

    {% empty %}
    <div style="text-align: center; padding-bottom: 10px; line-height: 1em;">
        <h3>You have no tasks</h3>
        <h3>Create a <a style="text-decoration: none; color: #e53935;" href="{% url 'task:task-create' %}">New task</a> ! </h3>
    </div>
    {% endfor %}
</div>

<script>
    var taskList = document.getElementById("tasklist");
    var reorderForm = document.getElementById("orderTask");
    var positionInput = document.getElementById("positionInput");

    let sortable = Sortable.create(taskList, {
        handle: '.handle',
        ghostClass: 'dropArea',
        chosenClass: 'selectedTask',

    });

    function reordering() {
        const rows = document.getElementsByClassName("task-wrapper");
        let pos = [];
        for (let row of rows) {
            pos.push(row.dataset.position);
        }
        console.log(pos.join(","))
        positionInput.value = pos.join(',');
        reorderForm.submit();
    }

    document.ondrop = reordering
</script>

{% endblock %}

task/templates/task/task_update.html
{% extends 'base.html' %}

{% block content %}
<div class="header-bar">
    <a href="{% url 'task:task-list' %}">&#8617; Back</a>
</div>


<h1>Update Task:</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="button" type="Submit" value="Submit">
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>To Do App</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@1,200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>